version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME: username
      # - MONGO_INITDB_ROOT_USERNAME=username
    env_file:
      - ./env/mongo.env
    
  # backend:
    
  # frontend:

volumes:
  data:
    